wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.10
    start_time: 1687371307
    t:
      1:
      - 1
      - 55
      3:
      - 13
      - 16
      4: 3.7.10
      5: 0.12.16
      8:
      - 5
epochs:
  desc: null
  value: 20
learning_rate:
  desc: null
  value: 0.01
